# Generated by Django 5.2.8 on 2026-03-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
