# Generated by Django 5.2.8 on 2026-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('photos', 'Photos'), ('stories', 'Stories'), ('tips', 'Tips'), ('reviews', 'Reviews'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
